version: '3.8'

services:
  # Django Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,frontend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - REDIS_URL=redis://redis:6379/0
      - CACHE_TIMEOUT=3600
      - RATELIMIT_ENABLE=True
      - RATELIMIT_RATE=100/h
      - ANIME_API_BASE_URL=https://hianime.bz
      - ANIME_API_BASE_URL_V2=https://kaido.to
      - ANIME_API_PROVIDERS=https://megacloud.club
    depends_on:
      - redis
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:8000 anime_api_project.wsgi:application
    networks:
      - hianime-network

  # Next.js Frontend
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - hianime-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hianime-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - hianime-network
    profiles:
      - proxy

volumes:
  redis_data:

networks:
  hianime-network:
    driver: bridge