version: '3.8'

services:
  # Django Backend (Development)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-not-for-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,frontend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - REDIS_URL=redis://redis:6379/0
      - CACHE_TIMEOUT=3600
      - RATELIMIT_ENABLE=True
      - RATELIMIT_RATE=100/h
      - ANIME_API_BASE_URL=https://hianime.bz
      - ANIME_API_BASE_URL_V2=https://kaido.to
      - ANIME_API_PROVIDERS=https://megacloud.club
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/staticfiles
      - /app/media
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - hianime-network

  # Next.js Frontend (Development)
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile.dev.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ../:/app
      - /app/node_modules
      - /app/.next
    networks:
      - hianime-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hianime-network

volumes:
  redis_data:

networks:
  hianime-network:
    driver: bridge